# Generated by Django 2.2.3 on 2019-07-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gmae',
            new_name='Game',
        ),
    ]
